version: '3.1'

services:
  # Use demo/demo as user/password credentials
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
    ports:
      - "5432:5432"
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "8081:8080"