version: '3.1'

services:
  # Use demo/demo as user/password credentials
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
    ports:
      - "5432:5432"
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "8081:8080"
  app1:
    image: spring-quartz-flyway-poc:0.0.1-SNAPSHOT
    container_name: app1
    restart: always
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: "jdbc:postgresql://db:5432/demo"
  app2:
    image: spring-quartz-flyway-poc:0.0.1-SNAPSHOT
    container_name: app2
    restart: always
    ports:
      - "8082:8080"
    environment:
      spring.datasource.url: "jdbc:postgresql://db:5432/demo"